baseURL = 'https://tenbulls.co.uk'
languageCode = 'en-us'
title = 'tenbulls blog'
theme = 'not-much'

# Controls the navigation
[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts"

[[menu.main]]
  identifier = "home"
  name = "home"
  title = "home"
  url = "https://tenbulls.co.uk"
  
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "about"
  url = "/"
