baseURL = 'https://tenbulls.co.uk'
languageCode = 'en-us'
title = 'tenbulls blog'
theme = 'not-much'
copyright = 'Copyright © {year} Mark Broadbent'

# Controls the navigation
[[menu.main]]
  identifier = "posts"
  name = "posts"
  title = "Posts"
  url = "/posts"

[[menu.main]]
  identifier = "home"
  name = "home"
  title = "home"
  url = "/"
  
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "about"
  url = "/about"

[[menu.main]]
  identifier = "meetup"
  name = "meetup"
  title = "meetup"
  url = "https://www.meetup.com/hybrid-virtual-group/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true